### PR TITLE
chore(deps): update dalek crypto deps

### PR DESCRIPTION
**Pull request by haraldh**

### CODE REVIEW

**Comment by haraldh** [comment]
clippy issues are not related to this PR and should probably be fixed separately.

**Comment by dignifiedquire** [comment]
thank you

**Comment by haraldh** [comment]
@dignifiedquire would be nice to have a release, because of:
https://github.com/advisories/GHSA-w5vr-6qhr-36cc

**Comment by haraldh** [comment]
```
 Dependabot cannot update ed25519-dalek to a non-vulnerable version

The latest possible version of ed25519-dalek that can be installed is 2.0.0-rc.3.

The earliest fixed version is 2.0.0.
```

**Comment by haraldh** [comment]
Let me know, if you need more help.

**Pull request merged**
