### PR TITLE
Add DSA verify implementation

### PR DESCRIPTION
**Pull request by rvolgers**
This handles no secret data and I'm reasonably confident in the
implementation, but I'm not sure what the standard is for accepting new
cryptographic implementations.

This is actually already covered by the test suite, the DSA signatures
were just being ignored previously.

### CODE REVIEW

**Comment by rvolgers** [comment]
Sigh. Please hold. I may have spotted a concern.

**Comment by rvolgers** [comment]
Okay, pretty sure that was a legitimate bug, and that it's fixed now. But this means this should probably have more tests.

**Comment by rvolgers** [comment]
Okay this has grown way beyond what I had planned, it's now a complete DSA implementation except for key generation.

Probably this would be better in an external crate. But I will leave this open in case there is interest.

**Comment by dignifiedquire** [comment]
A wild DSA implementation appeared 😄 
Thanks a lot, it will take me a little bit more time to review this, given it is an entirely new algorithm, but I definitely want to get it in. 

In the meantime, could you take a look at the CI failures please?

**Comment by rvolgers** [comment]
See related discussion in https://github.com/RustCrypto/signatures/pull/223

Most of this willl probably *eventually* go into RustCrypto. I'm not quite sure when though. If you want to merge this as is and later replace it with the implementation there that'd be fine too. But maybe keep this open for a little longer as I expect to add key generation as well, making it a pretty complete implementation.

**Comment by dignifiedquire** [comment]
closing in favor of #276

**Pull request closed without merging**
