### PR TITLE
chore: use a variable for "nightly", use a fixed nightly version for now

### PR DESCRIPTION
**Pull request by hko-s**
This nightly version avoids triggering the errors from https://github.com/dalek-cryptography/curve25519-dalek/issues/618

### CODE REVIEW

**Comment by hko-s** [comment]
Let's see if I can figure out how to do this in github CI :sweat_smile:

**Review by dignifiedquire — APPROVED** [review]

**Comment by dignifiedquire** [comment]
I think needs some more github actions foo 🤣

**Comment by hko-s** [comment]
> I think needs some more github actions foo 🤣

If you have a rough idea how to do this, I'd be happy to hand this over to you to fix?
I'm totally out of my element here, and might take a few hundred iterations :scream_cat:

**Comment by dignifiedquire** [comment]
I‘ll take a look tomorrow

**Pull request merged**
